"""empty message

Revision ID: 86fe94972c45
Revises: cd935c2db413
Create Date: 2018-05-04 13:08:51.671137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86fe94972c45'
down_revision = 'cd935c2db413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('ccode', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'countries', ['ccode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_column('countries', 'ccode')
    # ### end Alembic commands ###
