"""empty message

Revision ID: cd935c2db413
Revises: d4b4cf124228
Create Date: 2018-05-04 13:07:49.823521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd935c2db413'
down_revision = 'd4b4cf124228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('countries_ccode_key', 'countries', type_='unique')
    op.drop_column('countries', 'ccode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('ccode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('countries_ccode_key', 'countries', ['ccode'])
    # ### end Alembic commands ###
