"""empty message

Revision ID: d4b4cf124228
Revises: de86d7e9578e
Create Date: 2018-05-04 13:06:33.141421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b4cf124228'
down_revision = 'de86d7e9578e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'ccode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'countries', ['ccode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.alter_column('countries', 'ccode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
