"""empty message

Revision ID: de86d7e9578e
Revises: f848e19fd3fa
Create Date: 2018-05-04 12:42:51.788160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de86d7e9578e'
down_revision = 'f848e19fd3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('ccap', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'ccap')
    # ### end Alembic commands ###
