"""empty message

Revision ID: eba6c363b5f2
Revises: 
Create Date: 2018-05-03 20:45:35.692312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eba6c363b5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('flag_picture2', postgresql.BYTEA(), nullable=True),
    sa.Column('country_picture2', postgresql.BYTEA(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('president', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('population', mysql.BIGINT(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
