"""empty message

Revision ID: f848e19fd3fa
Revises: feb178e8a47a
Create Date: 2018-05-03 21:16:13.075030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f848e19fd3fa'
down_revision = 'feb178e8a47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('ccode', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('ccur', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('clang', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('cname', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('cpop', mysql.BIGINT(), nullable=True))
    op.add_column('countries', sa.Column('cpres', sa.String(), nullable=True))
    op.drop_column('countries', 'currency')
    op.drop_column('countries', 'population')
    op.drop_column('countries', 'language')
    op.drop_column('countries', 'parent_code')
    op.drop_column('countries', 'president')
    op.drop_column('countries', 'country_code')
    op.drop_column('countries', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('president', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('parent_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('population', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('countries', 'cpres')
    op.drop_column('countries', 'cpop')
    op.drop_column('countries', 'cname')
    op.drop_column('countries', 'clang')
    op.drop_column('countries', 'ccur')
    op.drop_column('countries', 'ccode')
    # ### end Alembic commands ###
